import { AspectRatioPreset, ThemeConfig } from '@/types';

export const ASPECT_RATIOS: AspectRatioPreset[] = [
  {
    id: '1:1',
    name: 'Instagram Post',
    category: 'Instagram',
    ratio: 1,
    width: 1080,
    height: 1080,
    label: '1:1 (1080 x 1080)',
  },
  {
    id: '9:16-tiktok',
    name: 'TikTok Post / Slideshow',
    category: 'TikTok',
    ratio: 9 / 16,
    width: 1080,
    height: 1920,
    label: '9:16 (1080 x 1920)',
  },
  {
    id: '3:4-tiktok',
    name: 'TikTok Photo Carousel',
    category: 'TikTok',
    ratio: 3 / 4,
    width: 1080,
    height: 1440,
    label: '3:4 (1080 x 1440)',
  },
  {
    id: '9:16-story',
    name: 'Instagram Story / Reels',
    category: 'Instagram',
    ratio: 9 / 16,
    width: 1080,
    height: 1920,
    label: '9:16 (1080 x 1920)',
  },
  {
    id: '4:5',
    name: 'Facebook & IG Portrait',
    category: 'Meta',
    ratio: 4 / 5,
    width: 1080,
    height: 1350,
    label: '4:5 (1080 x 1350)',
  },
  {
    id: '16:9',
    name: 'YouTube Thumbnail',
    category: 'YouTube',
    ratio: 16 / 9,
    width: 1920,
    height: 1080,
    label: '16:9 (1920 x 1080)',
  },
  {
    id: '16:9-twitter',
    name: 'Twitter / X Post',
    category: 'Twitter',
    ratio: 16 / 9,
    width: 1600,
    height: 900,
    label: '16:9 (1600 x 900)',
  },
  {
    id: '2:3',
    name: 'Pinterest Pin',
    category: 'Pinterest',
    ratio: 2 / 3,
    width: 1000,
    height: 1500,
    label: '2:3 (1000 x 1500)',
  },
  {
    id: 'custom',
    name: 'Custom Ratio',
    category: 'Custom',
    ratio: 1,
    width: 1080,
    height: 1080,
    label: 'Custom',
  },
];

export const THEMES: Record<string, ThemeConfig> = {
  neobrutalism: {
    id: 'neobrutalism',
    name: 'Neobrutalism',
    description: 'Bold black borders, vibrant pop colors & hard shadows',
    fontFamilyHeading: 'var(--font-neo-heading, "Plus Jakarta Sans", sans-serif)',
    fontFamilyBody: 'var(--font-neo-body, "Inter", sans-serif)',
    bgStyle: '#FEF08A', // Yellow pop
    cardStyle: '#FFFFFF',
    textColor: '#000000',
    headingColor: '#000000',
    accentColor: '#FF6B6B',
    borderStyle: '4px solid #000000',
    shadowStyle: '6px 6px 0px #000000',
    previewColor: '#FEF08A',
  },
  brutalism: {
    id: 'brutalism',
    name: 'Raw Brutalism',
    description: 'Monospace, stark contrast, sharp corners & raw vibe',
    fontFamilyHeading: 'Courier New, monospace',
    fontFamilyBody: 'Courier New, monospace',
    bgStyle: '#000000',
    cardStyle: '#18181B',
    textColor: '#00FF66',
    headingColor: '#FFFFFF',
    accentColor: '#00FF66',
    borderStyle: '3px solid #00FF66',
    shadowStyle: 'none',
    previewColor: '#000000',
  },
  minimalist: {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Clean typography, soft tones & serene whitespace',
    fontFamilyHeading: '"Inter", system-ui, sans-serif',
    fontFamilyBody: '"Inter", system-ui, sans-serif',
    bgStyle: '#F8FAFC',
    cardStyle: '#FFFFFF',
    textColor: '#334155',
    headingColor: '#0F172A',
    accentColor: '#3B82F6',
    borderStyle: '1px solid #E2E8F0',
    shadowStyle: '0 4px 20px -2px rgba(0, 0, 0, 0.05)',
    previewColor: '#F8FAFC',
  },
  'hand-drawn': {
    id: 'hand-drawn',
    name: 'Hand Drawn',
    description: 'Warm paper feel, organic borders & casual handwriting style',
    fontFamilyHeading: '"Comic Sans MS", "Chalkboard SE", cursive, sans-serif',
    fontFamilyBody: '"Comic Sans MS", "Chalkboard SE", cursive, sans-serif',
    bgStyle: '#FFFBEB',
    cardStyle: '#FEF3C7',
    textColor: '#78350F',
    headingColor: '#451A03',
    accentColor: '#D97706',
    borderStyle: '3px dashed #B45309',
    shadowStyle: '3px 3px 0px #78350F',
    previewColor: '#FFFBEB',
  },
  retro: {
    id: 'retro',
    name: 'Retro 80s',
    description: 'Vintage warm tones, nostalgic serif font & synthwave feel',
    fontFamilyHeading: 'Georgia, serif',
    fontFamilyBody: 'Georgia, serif',
    bgStyle: '#2D1B4E',
    cardStyle: '#3B2164',
    textColor: '#FDE047',
    headingColor: '#FF71CE',
    accentColor: '#01CDFE',
    borderStyle: '2px solid #FF71CE',
    shadowStyle: '4px 4px 0px #01CDFE',
    previewColor: '#2D1B4E',
  },
  flat: {
    id: 'flat',
    name: 'Flat Design',
    description: 'Clean solid colors, smooth geometry & crisp icons',
    fontFamilyHeading: '"Trebuchet MS", sans-serif',
    fontFamilyBody: '"Trebuchet MS", sans-serif',
    bgStyle: '#0EA5E9',
    cardStyle: '#38BDF8',
    textColor: '#FFFFFF',
    headingColor: '#FFFFFF',
    accentColor: '#F59E0B',
    borderStyle: 'none',
    shadowStyle: 'none',
    previewColor: '#0EA5E9',
  },
  bento: {
    id: 'bento',
    name: 'Bento Grid',
    description: 'Structured layout cards with rounded corners & modern dark aesthetic',
    fontFamilyHeading: 'system-ui, -apple-system, sans-serif',
    fontFamilyBody: 'system-ui, -apple-system, sans-serif',
    bgStyle: '#090D16',
    cardStyle: '#131B2E',
    textColor: '#94A3B8',
    headingColor: '#F8FAFC',
    accentColor: '#6366F1',
    borderStyle: '1px solid rgba(255, 255, 255, 0.1)',
    shadowStyle: '0 10px 30px rgba(0, 0, 0, 0.5)',
    previewColor: '#090D16',
  },
  glassmorphism: {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    description: 'Translucent frosted glass panels with vibrant neon glow',
    fontFamilyHeading: 'system-ui, sans-serif',
    fontFamilyBody: 'system-ui, sans-serif',
    bgStyle: 'linear-gradient(135deg, #0F172A 0%, #311B92 50%, #880E4F 100%)',
    cardStyle: 'rgba(255, 255, 255, 0.12)',
    textColor: '#E2E8F0',
    headingColor: '#FFFFFF',
    accentColor: '#38BDF8',
    borderStyle: '1px solid rgba(255, 255, 255, 0.25)',
    shadowStyle: '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
    previewColor: '#311B92',
  },
  gradient: {
    id: 'gradient',
    name: 'Vibrant Gradient',
    description: 'Smooth mesh gradient background with bold white typography',
    fontFamilyHeading: 'system-ui, sans-serif',
    fontFamilyBody: 'system-ui, sans-serif',
    bgStyle: 'linear-gradient(135deg, #FF416C 0%, #FF4B2B 100%)',
    cardStyle: 'rgba(255, 255, 255, 0.15)',
    textColor: '#FFFFFF',
    headingColor: '#FFFFFF',
    accentColor: '#FFD700',
    borderStyle: 'none',
    shadowStyle: '0 12px 40px rgba(255, 65, 108, 0.4)',
    previewColor: '#FF416C',
  },
};
